### ISSUE TITLE
Refactor zenoh_config.hpp so we can reuse it in the router

### ISSUE THREAD

**Issue by clalancette** [osrf/rmw_zenoh#102]
We have code in https://github.com/ros2/rmw_zenoh/blob/rolling/rmw_zenoh_cpp/src/detail/zenoh_config.hpp and https://github.com/ros2/rmw_zenoh/blob/rolling/rmw_zenoh_cpp/src/detail/zenoh_config.cpp that is currently used to allow the user to configure the *session* configuration when using `rmw_zenoh_cpp`.

We should also use that code to be able to configure *router* configuration as well.  That way, users will be able to launch the router locally with either the default config, or one they provide.  The code probably needs some refactoring to be able to use it for that purpose.

This is a follow-up task from #101 .

**Comment by Yadunund** [comment]
Closed via https://github.com/ros2/rmw_zenoh/pull/119
