### ISSUE TITLE
Remove dependency on `rmw_dds_common`

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmw_zenoh#104]
This ticket is a follow up to the discuss https://github.com/ros2/rmw_zenoh/pull/91#discussion_r1463661066

https://github.com/ros2/rmw_zenoh/pull/91 introduced a dependency on [rmw_dds_common](https://github.com/ros2/rmw_dds_common) to reuse certain methods to check for qos compatibility. However, the `zenoh` protocol is generally more tolerable to QoS mismatches that `rmw_dds_common` might flag as incompatible. By relying on `rmw_dds_common`, we  retain the incompatibility warnings despite transport delivering message payloads.

We should drop the `rmw_dds_common` dependency in the future and implement qos compatibility methods that better reflect the `zenoh` protocol.

**Comment by clalancette** [comment]
We did this in #234, so closing this out.
