### ISSUE TITLE
Items to finish before Jazzy release

### ISSUE THREAD

**Issue by clalancette** [osrf/rmw_zenoh#110]
This issue puts together the list of items, in rough priority order, that should be completed on rmw_zenoh_cpp before Jazzy.  Not all of these are strictly required, as basic functionality is already there, but having all of these will go a long way towards making rmw_zenoh_cpp something that people can actively try out.

| Status | Item | Why? | Related issues/PRs |
|-----------------|--------|----------|-----------------------------|
| Complete | Events support  | Required for `rviz2`, `ros2 topic`, and other tools | https://github.com/ros2/rmw_zenoh/pull/103 |
| Complete | Build rmw_zenoh_cpp on Ubuntu 24.04 with rustc on that OS | Will be necessary to tell users how to use rmw_zenoh | https://github.com/ros2/rmw_zenoh/pull/136 |
| Complete | Implement `rmw_take_serialized_message{_with_info}` | Required for rosbag2 | #113 |
| Complete | Implement `rmw_get_gid_for_client` | Required to support service introspection | #115 |
| Complete | Implement `rmw_get_gid_for_publisher` | We are currently lying to the upper levels, so should fix that | #116 |
| Not started | Implement `rmw_publisher_wait_for_all_acked` | Required to support rclcpp/rclpy `wait_for_all_acked`, used in tests | |
| Complete | Allow the user to pass a custom config file to `init_rmw_zenoh_router` | User customization of zenohd will be important | #119 |
| Complete | Fill in the source timestamp and GID for published messages | End-users expect this information to be there | #123 |
| Not started | Restrict Zenoh sessions/router to a specific network interface | Important for certain use cases, like Velodyne sensors which use ethernet | |
| Complete | Run rmw_zenoh_cpp against all tests in the ROS 2 core | This will give us much more confidence in the things we have implemented, and show us weaknesses | https://github.com/ros2/rmw_zenoh/issues/162, https://github.com/ros2/rmw_zenoh/issues/161, https://github.com/ros2/rmw_zenoh/issues/156, https://github.com/ros2/rmw_zenoh/issues/154, https://github.com/ros2/rmw_zenoh/issues/151 |
| Complete | Revisit how and when to start the zenoh router; should we do it all, should we do it automatically, or should we make the user do it? | Starting it automatically makes it more seamless, but gives the user less opportunity to configure.  Need to consider the tradeoffs and what the default should be | https://github.com/ros2/rmw_zenoh/pull/135 |

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-meeting-minutes-2024-02-15/36221/1

**Comment by clalancette** [comment]
Closing this one out, as we are post-Jazzy and working on other parts of `rmw_zenoh_cpp` now.
