### ISSUE TITLE
Revisit anonymous namespaces vs. static functions

### ISSUE THREAD

**Issue by clalancette** [osrf/rmw_zenoh#124]
C++ has two different ways to create compilation-unit-local functions: using an anonymous namespace (the modern C++ way), or by putting `static` in front of the function (the C way).

Currently in rmw_zenoh_cpp we use a mixture of these two styles.  We should be consistent here, and just choose one.  My personal preference is for `static` in front of the function, as it is easier to tell at a glance that a function is local-only.  But I'm open to other opinions.

This comes out of a discussion in https://github.com/ros2/rmw_zenoh/pull/123#discussion_r1512108913

**Comment by fujitatomoya** [comment]
@clalancette can you assign this to @Yadunund ?
