### ISSUE TITLE
Cannot compile in debug mode

### ISSUE THREAD

**Issue by Timple** [osrf/rmw_zenoh#165]
We typically have a colcon defaults file containing:
```
 - "-DCMAKE_BUILD_TYPE=Debug"
 - "-DCMAKE_CXX_FLAGS=-O2"
```
In order to still catch asserts in our code. However `rmw_zenoh` doesn't compile with these settings. With `RelWithDebInfo` it does.

**Comment by clalancette** [comment]
Hm, I just tried it here, and it seems to compile for me:

```
colcon build --event-handler console_direct+ --cmake-args -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-O2 --packages-select rmw_zenoh_cpp
```

In this test, I was on Ubuntu 22.04, building against Iron.  Can you give me more information about your setup?

**Comment by Timple** [comment]
I can, I'll try to make a reproducable docker. 
But what I already notice is you're not compiling `zenoh_c_vendor`. So I'd make it `--packages-up-to` in a clean workspace.

**Comment by clalancette** [comment]
> But what I already notice is you're not compiling `zenoh_c_vendor`. So I'd make it `--packages-up-to` in a clean workspace.

Ah, OK.  I'll give it a try.

**Comment by clalancette** [comment]
OK, now I see the problem.  For some reason when you build `zenoh_c` in Debug mode, it actually changes the name of the CMake config file to `zenohc_debug`, which we weren't looking for.  I'll open a patch to fix this shortly.

**Comment by Timple** [comment]
Awesome, thanks for diving in!
