### ISSUE TITLE
Missing install 'ros-jazzy-desktop' 

### ISSUE THREAD

**Issue by niektuytel** [osrf/rmw_zenoh#183]
[missing the ros-jazzy-desktop package](https://docs.ros.org/en/jazzy/Installation/Ubuntu-Install-Debians.html)
![image](https://github.com/ros2/rmw_zenoh/assets/46424968/8e03bfe8-ae38-4bab-a8f0-55710bae03e6)

The error message
![image](https://github.com/ros2/rmw_zenoh/assets/46424968/2895327e-852e-4191-8eee-7d937159effa)

**Comment by niektuytel** [comment]
i have the same issue on `E: Unable to locate package ros-humble-desktop`

Maybe for me the issue is ubuntu version?
![image](https://github.com/ros2/rmw_zenoh/assets/46424968/0b52d2fd-caef-4cb0-92a4-4f44ec1df049)

**Comment by mjcarroll** [comment]
The zenoh repo is very likely the wrong place to ask this question as it doesn't have anything to specifically do with rmw_zenoh.

There are no active ROS releases support 20.04 as a Tier 1 platform.  You can probably compile `humble` from source, but binary `humble` packages require 22.04 and binary `jazzy` packages require 24.04.

For current platform support, consult: https://www.ros.org/reps/rep-2000.html
