### ISSUE TITLE
Make rmw_service_server_is_available return RMW_RET_INVALID_ARGUMENT

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmw_zenoh#194]
Follow up to https://github.com/ros2/rmw_implementation/pull/231. 

> Note: We might need to create `iron` and `jazzy` branches, before we adopt this change.

**Comment by christophebedard** [comment]
FYI I believe `rmw_zenoh_cpp` already returns `RMW_RET_INVALID_ARGUMENT` in this case.

**Comment by Yadunund** [comment]
Oops I didn't check the implementation before I opened this ticket. But glad to see that.
