### ISSUE TITLE
Is shm used in nodes connected in the same SOC

### ISSUE THREAD

**Issue by sgf201** [osrf/rmw_zenoh#199]
As I see,zenoh can use shm for msg ,Is shm used in rmw_zenoh?

**Comment by Yadunund** [comment]
Preliminary efforts were made to support SHM but certain memory leaks were discovered. Hence, SHM is disabled by default in [the session config](https://github.com/ros2/rmw_zenoh/blob/1caf7f1c55e7f5f04c3511b19d172571e732f42e/rmw_zenoh_cpp/config/DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5#L234-L235).

**Comment by sgf201** [comment]
as I see, loan api of ros2 is UNSUPPORTED now, will it supported with shm in roadmap?

**Comment by ruffsl** [comment]
> Hence, SHM is disabled by default

@Yadunund , is there some context for that. From git blame of that config line, is this perhaps all of it?
- https://github.com/ros2/rmw_zenoh/pull/91#issuecomment-1907298304
- https://github.com/ros2/rmw_zenoh/commit/a9b424505c55411dd37db402eae91663673980e8

**Comment by Yadunund** [comment]
> > Hence, SHM is disabled by default
> 
> @Yadunund , is there some context for that. From git blame of that config line, is this perhaps all of it?
> 
> * [Support basic QoS settings #91 (comment)](https://github.com/ros2/rmw_zenoh/pull/91#issuecomment-1907298304)
> * [a9b4245](https://github.com/ros2/rmw_zenoh/commit/a9b424505c55411dd37db402eae91663673980e8)

It's an issue in the Zenoh implementation. See https://github.com/eclipse-zenoh/zenoh/issues/406.

My understanding is that Zettascale is working on a true-zero-copy alternative so we're likely going to wait for that to land and update our SHM implementation accordingly.

**Comment by JEnoch** [comment]
That's right, a new shared memory will be available very soon with Zenoh 1.0.0.
The development in Rust is already completed, and the C API has been merged to the `dev/1.0.0` branch last week:
https://github.com/eclipse-zenoh/zenoh-c/pull/405

**Comment by kikuyuta** [comment]
That's a great news!
According to my understanding, currently we can use zenoh-pico for poor capability chips e.g. ESP32.
Will zenoh 1.0.0, the Rust version with shared memory functionality, work on such poor chips? Or will zenoh-pico also have SHM functionality?

**Comment by JEnoch** [comment]
There is no plan for a Zenoh Rust for constrained devices, neither for SHM in zenoh-pico.
But the Zenoh team is always eager to learn about new use cases and to get suggestions of new features. 😃 
Please, feel free to open a discussion here:
https://github.com/eclipse-zenoh/roadmap/discussions/categories/ideas-and-new-features

**Comment by kikuyuta** [comment]
@JEnoch Thank you for your reply.
Okay I will open a new discussion there, but later, because it is past midnight in Japan.

**Comment by sgf201** [comment]
> as I see, loan api of ros2 is UNSUPPORTED now, will it supported with shm in roadmap?

can you give me a bref info about this?
@JEnoch
