### ISSUE TITLE
Drop usage of `rmw_dds_common::qos_profile_get_best_available_X`

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmw_zenoh#212]
At the same time explore transmitting QoS info only if there is a deviation from the system default. See https://github.com/ros2/rmw_zenoh/pull/210#discussion_r1652776472 for context.

**Comment by clalancette** [comment]
We've now dropped our usage of `rmw_dds_common` completely, so I'm going to go ahead and close this out.
