### ISSUE TITLE
Race conditions when accessing data

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmw_zenoh#249]
The current implementation suffers from data races between threads that access the same data, eg. [rmw_publisher_data_t](https://github.com/ros2/rmw_zenoh/blob/fcfed30ca7ba629a137bc48fab0502c71e515839/rmw_zenoh_cpp/src/detail/rmw_data_types.hpp#L94). There are essentially two classes of races:
1. One thread destructing the data object and another accessing is modifying it.
2. Two or more threads are modifying the data object.

### Proposal to address the issue
- [ ] Update all data classes to rely on getters and setters to access members while locking mutexes.
- [ ] The type erased data fields in rmw types, eg [rmw_publisher_t->data](https://github.com/ros2/rmw/blob/5ce844c23131113f14102ad45aac009142bafa9a/rmw/include/rmw/types.h#L128) will store the raw pointer to the RMW context. The assumption here is that the context will always be valid if an RMW entity is valid
- [ ] The [rmw_context_impl_s](https://github.com/ros2/rmw_zenoh/blob/fcfed30ca7ba629a137bc48fab0502c71e515839/rmw_zenoh_cpp/src/detail/rmw_data_types.hpp#L46) class will store sets/vectors of `rmw_x_data_t` objects of the various RMW entities (publishers, subs, clients, servers, etc). Two or more threads will lock the same mutex in the `rmw_context_impl_s` while accessing/modifying these objects.

**Comment by clalancette** [comment]
I believe that this has been done with a combination of refactors from @Yadunund , plus the switch to zenoh-cpp.  Thus I'm going to close this out.
