### ISSUE TITLE
Console Doesn't Revert To Old Console Mode After Router Process Is Terminated

### ISSUE THREAD

**Issue by CihatAltiparmak** [osrf/rmw_zenoh#251]
Hello,

In router executable, SIGINT signal is handled but SIGTERM is not handled. This gives rise not to close router gracefully. If we directly send SIGTERM to router, router doesn't close session and KeyboardReader instance doesn't destroy. Additionaly, When it is threw out reading error from tty, we should close session before finishing process. I have a PR for it.

**Comment by DarkusAlphaHydranoid** [comment]
PR is merged. Can be closed.
