### ISSUE TITLE
[Feature request] Introduce `clang_format` and `clang_tidy`

### ISSUE THREAD

**Issue by YuanYuYuan** [osrf/rmw_zenoh#253]
While porting rmw_zenoh to 1.0, it's sometimes hard to align the code style since `cpplint` doesn't provide a reformat/inplace option like `ament_uncrustify`. It would be nice to adapt the modern solutions like the linter `clang_tidy` and the formatter `clang_format` as we do in our zenoh c/cpp projects and as [moveit](https://github.com/moveit/moveit2/blob/main/.clang-format) do in their project. These checks can easily integrated with the editor and into the CI. If you think it's a good idea, I'm happy to make a PR for it. :smiley:

**Comment by clalancette** [comment]
> It would be nice to adapt the modern solutions like the linter `clang_tidy` and the formatter `clang_format`

I'd really rather not.  The goal here is to make `rmw_zenoh` part of the main ROS 2 core, and there we use both `cpplint` and `uncrustify`.

That said, in my experience if you use the `--reformat` option with `cpplint`, that gets you 90% of the way to making it compliant with `cpplint`.
