### ISSUE TITLE
Towards Windows support

### ISSUE THREAD

**Issue by ahcorde** [osrf/rmw_zenoh#268]
I installed `rust` and `mingw` using `chocolatey`

```bash
choco install -y rust mingw
```

But I'm getting this error:

```
    CMake Error at install/cmake_install.cmake:59 (file):
      file INSTALL cannot find
      "C:/rolling/build/zenoh_c_vendor/zenoh_c_vendor-prefix/src/zenoh_c_vendor-build/release/target/release/zenohc.dll.lib":
      No error.
    Call Stack (most recent call first):
      cmake_install.cmake:37 (include)
```

Not sure why `.lib` is added at the end of the file name

**Comment by Yadunund** [comment]
Perhaps you can try with this commit of zenoh-c?
https://github.com/eclipse-zenoh/zenoh-c/pull/471

**Comment by ahcorde** [comment]
https://github.com/ros2/rmw_zenoh/pull/273

**Comment by ahcorde** [comment]
the zenoh_cpp port is compiling on windows https://github.com/ros2/rmw_zenoh/pull/327

closing this issue
