### ISSUE TITLE
Check for router connectivity more often

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmw_zenoh#277]
At present we retry the check for a router every 1s which may be slow. We should reduce this down to 100ms as recommended https://github.com/ros2/rmw_zenoh/pull/258#discussion_r1710194598

**Comment by evshary** [comment]
Yes, we also came across the issue while doing tests. It severely affects the time to do a full system test.
https://github.com/ZettaScaleLabs/rmw_zenoh/issues/12
I think we can move this line into the if-condition, which means only waiting if the router is not found.
However, it will cause some liveliness issues in Zenoh. We'll update the liveliness mechanism later.
For the time being, reducing the sleep time might be a better option.
