### ISSUE TITLE
Update to Zenoh 1.0.0

### ISSUE THREAD

**Issue by mgeisslinger** [osrf/rmw_zenoh#300]
Right now, rmw_zenoh points to zenoh version `0.11.0` which still has several bugs, for example https://github.com/eclipse-zenoh/zenoh/issues/1018, which is especially relevant for larger projects with lots of ROS nodes.

Are there any plans to bump to zenoh `1.0.0` here?

**Comment by clalancette** [comment]
Yes, see #276
