### ISSUE TITLE
Question high frequency small message publishing

### ISSUE THREAD

**Issue by Tacha-S** [osrf/rmw_zenoh#314]
The default configuration of `rmw_zenoh` does not handle high-frequency,
small-message topics (such as `/clock` published at 1000 Hz) very well, 
causing the topic frequency to decrease. 

I’ve noticed that reducing `transport.link.tx.batch_size` improves performance.
Does this mean rmw_zenoh always waits until the maximum batch size is filled before sending data?

Additionally, when I set the `batch_size` to `1`, 
other nodes fail to connect to the router at startup, 
displaying the following message:

```
Unable to connect to a Zenoh router. Have you started a router with ros2 run rmw_zenoh_cpp rmw_zenohd?
```

Is there an optimal configuration for handling high-frequency topics while maintaining router connectivity?

**Comment by JEnoch** [comment]
The best solution is to disable batching for this topic.
This configuration is not yet available in `rolling` branch which was using Zenoh 0.11.0. 
But you can test it using the [fork/branch](https://github.com/ZettaScaleLabs/rmw_zenoh/tree/dev/1.0.0) used for porting to Zenoh 1.0.0. [Here](https://github.com/ZettaScaleLabs/rmw_zenoh/blob/8557523723e27b519b40fff1b0f0ae78cd3c729d/rmw_zenoh_cpp/config/DEFAULT_RMW_ZENOH_SESSION_CONFIG.json5#L415) is the config flag to totally disable batching.
If your `/clock` subscriber is on a remote host with Zenoh Routers as intermediaries, you probably have to also disable batching for the Routers.

How many Nodes are subscribing toe the `/clock` topic, and what are your platform details (hardware, OS, docker?).
This would help us to understand if we can improve the batching behaviour for such use case, or if we need to disable it by default for ROS (maybe only in Sessions config 🤔)

**Comment by Tacha-S** [comment]
With version 1.0.0, this issue might be resolved even if batching is enabled.
Although we're seeing a large number of `topic name ** not found in topic_map. Report this.` messages, making it somewhat unstable,
`/clock` is still outputting at the ideal frequency under the default settings of 1.0.0.

For reference, here is our operating environment:

- OS: Ubuntu 24.04
- Number of `/clock` subscribers: 41
- Ideal `/clock` frequency: 1000 Hz
- Actual frequency: 200–300 Hz (with zenoh 0.11.0 default settings)

**Comment by JEnoch** [comment]
Thank you for your quick test and reply.
Improvements have been made on batching in Zenoh 1.0.0. Good to know it's already solving your issue !

> Although we're seeing a large number of topic name ** not found in topic_map. Report this. messages, making it somewhat unstable,

Can you please create a new issue for this, with more details such as deployments view, configs and logs.

Then I think this issue can be closed @clalancette
