### ISSUE TITLE
Handle errors in parsing liveliness tokens

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmw_zenoh#72]
Something to be discussed is how to best handle errors in liveliness token subscriptions. Right now, an error message will be printed but should the node continue to function if transport works? See https://github.com/ros2/rmw_zenoh/pull/70#discussion_r1409742683

**Comment by clalancette** [comment]
Personally I think that we should detect the errors, report them once, ignore it, and then continue on.  That will help deal with the case of a malicious actor intentionally publishing bogus liveliness tokens.

**Comment by Yadunund** [comment]
Handled in #103
