### ISSUE TITLE
Investigate potential bug in rmw API 

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmw_zenoh#74]
`rmw_shutdown()` is invoked by `rcl` before `rmw_destroy_node()`. See https://github.com/ros2/rmw_zenoh/blob/85698981dafe966f18b83a525875436c8443476a/rmw_zenoh_cpp/src/rmw_init.cpp#L372-L375

**Comment by clalancette** [comment]
This is by design; see #92.  Closing this one out.
