### ISSUE TITLE
Incorrect error handling when zenoh router node is terminated 

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmw_zenoh#78]
Killing the router node (Crtl+C) started by `ros2 run rmw_zenoh_cpp init_rmw_zenoh_router` will return this error 
```bash
^CFailed to run zenoh router: zenohd -c ../ws_rmw/install/rmw_zenoh_cpp/share/rmw_zenoh_cpp/config/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
```

We should try to handle sigint and sigterm cases in this return https://github.com/ros2/rmw_zenoh/blob/beb9fd880227375c1f81b9ca8be06978a826fe04/rmw_zenoh_cpp/apps/init_rmw_zenoh_router.cpp#L36

**Comment by clalancette** [comment]
#99 somewhat addresses this, so closing.
